spring:
  datasource:
    url: jdbc:h2:./appdb
    username: sa
    password: admin

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
server:
  port: 8030

